# Don't edit this file, user DockerfileTemplate and buildImage.sh
###############################################
FROM registry.services.alin.be/google/cadvisor:v0.29.0
COPY localtime /etc/localtime
COPY .htpasswd .htpasswd
