# Don't edit this file, user DockerfileTemplate and buildImage.sh
###############################################
FROM registry.services.alin.be/google/cadvisor:v0.30.2
COPY localtime /etc/localtime
COPY .htpasswd .htpasswd
