version: '3.4'

services:
  cadvisor:
    image: cadvisor-image
    deploy:
      mode: global
      resources:
        limits:
          cpus: "0.3"
          memory: 100M
      restart_policy:
        condition: on-failure
      labels:
        - traefik.port=8080
        - traefik.frontend.rule=Host:cadvisor.services.alin.be
        - traefik.frontend.entryPoints=http,https
        - traefik.backend.loadbalancer.method=wrr
        - traefik.frontend.auth.basic=admin:$$apr1$$gWiqD1WO$$kJ1Im7XyH2pH5V/D/DmcL.
    volumes:
       - /:/rootfs:ro
       - /var/run:/var/run:rw
       - /sys:/sys:ro
       - /var/lib/docker/:/var/lib/docker:ro
       - /dev/disk/:/dev/disk:ro

networks:
  default:
    external:
      name: traefik-net
