version: '3.5'

services:
  cadvisor:
    image: registry.services.alin.be/cadvisor-alin:v1
    deploy:
      mode: global
      resources:
        limits:
          cpus: "0.3"
          memory: 100M
      restart_policy:
        condition: on-failure
      labels:
        - traefik.port=8080
        - traefik.frontend.rule=Host:cadvisor.services.alin.be
        - traefik.frontend.entryPoints=http,https
        - traefik.backend.loadbalancer.method=wrr
    volumes:
       - /:/rootfs:ro
       - /var/run:/var/run:rw
       - /sys:/sys:ro
       - /var/lib/docker/:/var/lib/docker:ro
       - /dev/disk/:/dev/disk:ro
    command: --http_auth_file .htpasswd --http_auth_realm cadvisor

networks:
  default:
    external:
      name: traefik-net
